# CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  ctrz: circleci/docker-publish@0.1.6

jobs:
  env:
    docker:
    - image: alpine:latest
    steps:
    - run:
        command: env

workflows:
  version: 2
  build_docker_image:
    jobs:
      - env
      - ctrz/publish:
          deploy: false
          extra_build_args: --build-arg DOCKER_LOGIN=scheetz
