# CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.6

jobs:
  env:
    docker:
    - image: alpine:latest
    steps:
    - run:
      command: env
  ctrz:
    executor: docker-publish/docker
    environment:
      DOCKER_LOGIN: scheetz
    steps:
    - checkout
    - setup_remote_docker
    - docker-publish/check
    - docker-publish/build

workflows:
  version: 2
  build_docker_image:
    jobs:
      - env
      - ctrz
