# CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@4.0.1

workflows:
  version: 2
  build_docker_image:
    jobs:
      - aws-ecr/build_and_push_image:
          context: ecr
          create-repo: true
          repo: $CIRCLE_REPOSITORY_URL
